<?php
/**
 * SSL Configuration for Development
 * Auto-generated by fix_ssl_permanently.php
 */

// Disable SSL verification for development environments only
if (strpos(__DIR__, 'wamp') !== false || strpos(__DIR__, 'xampp') !== false || 
    $_SERVER['SERVER_NAME'] === 'localhost' || $_SERVER['SERVER_NAME'] === '127.0.0.1') {
    
    // Set default cURL options to disable SSL verification
    $curlDefaults = [
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => false,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_CONNECTTIMEOUT => 30
    ];
    
    // Set default stream context
    stream_context_set_default([
        'ssl' => [
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true
        ],
        'http' => [
            'timeout' => 30
        ]
    ]);
}
?>